### ISSUE TITLE
example behind login

### ISSUE THREAD

**Issue by davidvasandani** [david-torres/skrapa#2]
Thanks for the great app @david-torres. Would it be possible to use Skrapa to login to a website before scraping, for example amazon.com? Cheers!

**Comment by david-torres** [comment]
Doesn't support that currently but the underlying engine, Colly, does. I should be able to add that in pretty easily. Will post back here when it's available.

**Comment by david-torres** [comment]
I looked into this. I was able to get something very basic working, but unfortunately I couldn't get any real world examples (e.g. amazon) working because of various login protections that sites implement such as CSRF tokens.
